# Generated by Django 5.0.2 on 2024-03-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_table'),
        ('reception', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.table'),
        ),
    ]
