# Generated by Django 5.0.3 on 2024-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('usy', 'Busy')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('day', 'Day'), ('evening', 'Evening')], max_length=250),
        ),
    ]
