# Generated by Django 5.0.2 on 2024-03-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_waiter_status_alter_waiter_shift'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='orders',
            field=models.ManyToManyField(related_name='waiters', to='order.order'),
        ),
    ]
