# Generated by Django 5.0.2 on 2024-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_waiter_orders'),
        ('order', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='orders',
            field=models.ManyToManyField(related_name='waiters', to='order.order'),
        ),
    ]
